goreleaser: fix linux packages
The `provides` should not be set, and it was breaking at least alpine.

To reproduce:

```
$ MAKE_LATEST_RELEASE=false goreleaser release --skip=publish --clean --snapshot
$ docker run --rm -ti -v `pwd`:/app -w /app alpine sh
```

Before:

```
ERROR: unable to select packages:
  plakar-1.0.3_SNAPSHOT-e146d86d-r1:
    conflicts: plakar-1.0.3_SNAPSHOT-e146d86d-r1[plakar]
    satisfies: world[plakar><Q1pxT9WcBHUnSqkArquBJdMbiWqBA=]
```

Now: installation si correct.